---

- name: service - configuring service
  service:
    name: mongod
    state: stopped
    enabled: no

- name: service - remove default service
  file:
    state=absent
    path={{ item }}
  with_items:
    - /etc/init.d/mongod
    - /etc/init/mongod.*

- name: service - numactl
  shell: "$(which numactl) -- --interleave=all"
  ignore_errors: yes
  register: numa_cmd

- debug: var=numa_cmd.stdout

- name: service - runit
  runit:
    name: mongodb
    enabled: true
    state: start
    timeout: 300
    user:  "{{ mongodb_user }}"
    command: "{{ numa_cmd.stdout }} /usr/bin/mongod --config /etc/mongod.conf"
  register: mongod_service_status

