---

- name: restart mongodb
  runit:
    name=mongodb
    enabled=true
    state=up
    timeout=300
    action=restart
  when: not (mongod_service_status is defined and mongod_service_status.restarted) 

